// <auto-generated />
using System;
using ENPS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ENPS.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210325020202_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CAD_empresaCAD_endereco", b =>
                {
                    b.Property<int>("CAD_EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("CAD_enderedoId")
                        .HasColumnType("int");

                    b.HasKey("CAD_EmpresaId", "CAD_enderedoId");

                    b.HasIndex("CAD_enderedoId");

                    b.ToTable("CAD_empresaCAD_endereco");
                });

            modelBuilder.Entity("CAD_enderecoCAD_pessoa", b =>
                {
                    b.Property<int>("CAD_EnderecoId")
                        .HasColumnType("int");

                    b.Property<int>("CAD_PessoaId")
                        .HasColumnType("int");

                    b.HasKey("CAD_EnderecoId", "CAD_PessoaId");

                    b.HasIndex("CAD_PessoaId");

                    b.ToTable("CAD_enderecoCAD_pessoa");
                });

            modelBuilder.Entity("ENPS.Models.CAD_CNPJ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CAD_CNPJ");
                });

            modelBuilder.Entity("ENPS.Models.CAD_CPF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CAD_CPF");
                });

            modelBuilder.Entity("ENPS.Models.CAD_Telefone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CAD_empresaId")
                        .HasColumnType("int");

                    b.Property<int?>("CAD_pessoaId")
                        .HasColumnType("int");

                    b.Property<int>("CodigoEstado")
                        .HasColumnType("int");

                    b.Property<int>("CodigoPais")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<bool>("Princial")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CAD_empresaId");

                    b.HasIndex("CAD_pessoaId");

                    b.ToTable("CAD_Telefone");
                });

            modelBuilder.Entity("ENPS.Models.CAD_email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CAD_empresaId")
                        .HasColumnType("int");

                    b.Property<int?>("CAD_pessoaId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Princial")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CAD_empresaId");

                    b.HasIndex("CAD_pessoaId");

                    b.ToTable("CAD_Email");
                });

            modelBuilder.Entity("ENPS.Models.CAD_empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CAD_CNPJId")
                        .HasColumnType("int");

                    b.Property<int?>("CAD_UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("COF_cidadeId")
                        .HasColumnType("int");

                    b.Property<int?>("COF_estadoId")
                        .HasColumnType("int");

                    b.Property<string>("Fantasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CAD_CNPJId");

                    b.HasIndex("CAD_UsuarioId");

                    b.HasIndex("COF_cidadeId");

                    b.HasIndex("COF_estadoId");

                    b.ToTable("CAD_empresa");
                });

            modelBuilder.Entity("ENPS.Models.CAD_empresaCAD_email", b =>
                {
                    b.Property<int>("CAD_empresaId")
                        .HasColumnType("int");

                    b.Property<int>("CAD_emailId")
                        .HasColumnType("int");

                    b.HasKey("CAD_empresaId", "CAD_emailId");

                    b.ToTable("CAD_empresaCAD_email");
                });

            modelBuilder.Entity("ENPS.Models.CAD_empresaCAD_endereco", b =>
                {
                    b.Property<int>("CAD_empresaId")
                        .HasColumnType("int");

                    b.Property<int>("CAD_enderecoId")
                        .HasColumnType("int");

                    b.HasKey("CAD_empresaId", "CAD_enderecoId");

                    b.ToTable("CAD_empresaCAD_Endereco");
                });

            modelBuilder.Entity("ENPS.Models.CAD_empresaCAD_telefone", b =>
                {
                    b.Property<int>("CAD_empresaId")
                        .HasColumnType("int");

                    b.Property<int>("CAD_telefoneId")
                        .HasColumnType("int");

                    b.HasKey("CAD_empresaId", "CAD_telefoneId");

                    b.ToTable("CAD_empresaCAD_telefone");
                });

            modelBuilder.Entity("ENPS.Models.CAD_endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("COF_CidadeId")
                        .HasColumnType("int");

                    b.Property<int?>("COF_EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("COF_CidadeId");

                    b.HasIndex("COF_EstadoId");

                    b.ToTable("CAD_endereco");
                });

            modelBuilder.Entity("ENPS.Models.CAD_pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CAD_CPFId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CAD_CPFId");

                    b.ToTable("CAD_Pessoa");

                    b.HasDiscriminator<string>("Discriminator").HasValue("CAD_pessoa");
                });

            modelBuilder.Entity("ENPS.Models.CAD_pessoaCAD_email", b =>
                {
                    b.Property<int>("CAD_pessoaId")
                        .HasColumnType("int");

                    b.Property<int>("CAD_emailId")
                        .HasColumnType("int");

                    b.HasKey("CAD_pessoaId", "CAD_emailId");

                    b.HasIndex("CAD_emailId");

                    b.ToTable("CAD_pessoaCAD_email");
                });

            modelBuilder.Entity("ENPS.Models.CAD_pessoaCAD_endereco", b =>
                {
                    b.Property<int>("CAD_pessoaId")
                        .HasColumnType("int");

                    b.Property<int>("CAD_enderecoId")
                        .HasColumnType("int");

                    b.HasKey("CAD_pessoaId", "CAD_enderecoId");

                    b.ToTable("CAD_pessoaCAD_endereco");
                });

            modelBuilder.Entity("ENPS.Models.CAD_pessoaCAD_redeSocial", b =>
                {
                    b.Property<int>("CAD_pessoaId")
                        .HasColumnType("int");

                    b.Property<int>("CAD_RedeSocialId")
                        .HasColumnType("int");

                    b.HasKey("CAD_pessoaId", "CAD_RedeSocialId");

                    b.ToTable("CAD_pessoaCAD_redeSocial");
                });

            modelBuilder.Entity("ENPS.Models.CAD_pessoaCAD_telefone", b =>
                {
                    b.Property<int>("CAD_pessoaId")
                        .HasColumnType("int");

                    b.Property<int>("CAD_telefone_id")
                        .HasColumnType("int");

                    b.HasKey("CAD_pessoaId", "CAD_telefone_id");

                    b.ToTable("CAD_pessoaCAD_telefone");
                });

            modelBuilder.Entity("ENPS.Models.CAD_redeSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CAD_pessoaId")
                        .HasColumnType("int");

                    b.Property<int>("ERedeSocial")
                        .HasColumnType("int");

                    b.Property<string>("LinkRedeSocial")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CAD_pessoaId");

                    b.ToTable("CAD_redeSocial");
                });

            modelBuilder.Entity("ENPS.Models.COF_Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("CEP")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("COF_Cidade");
                });

            modelBuilder.Entity("ENPS.Models.COF_Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("COF_Estado");
                });

            modelBuilder.Entity("ENPS.Models.COF_pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("COF_pais");
                });

            modelBuilder.Entity("ENPS.Models.NPS_Pesquisa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CAD_empresaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFechamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdOperador")
                        .HasColumnType("int");

                    b.Property<int>("NotaMaxima")
                        .HasColumnType("int");

                    b.Property<int>("NotaMinima")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CAD_empresaId");

                    b.ToTable("NPS_Pesquisa");
                });

            modelBuilder.Entity("ENPS.Models.NPS_votacao", b =>
                {
                    b.Property<int>("nPS_PesquisaId")
                        .HasColumnType("int");

                    b.Property<int>("cAD_pessoaId")
                        .HasColumnType("int");

                    b.Property<string>("LinkVotacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.HasKey("nPS_PesquisaId", "cAD_pessoaId");

                    b.HasIndex("cAD_pessoaId");

                    b.ToTable("NPS_votacao");
                });

            modelBuilder.Entity("ENPS.Models.CAD_Usuario", b =>
                {
                    b.HasBaseType("ENPS.Models.CAD_pessoa");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("SenhaHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SenhaSalt")
                        .HasColumnType("varbinary(max)");

                    b.HasDiscriminator().HasValue("CAD_Usuario");
                });

            modelBuilder.Entity("CAD_empresaCAD_endereco", b =>
                {
                    b.HasOne("ENPS.Models.CAD_empresa", null)
                        .WithMany()
                        .HasForeignKey("CAD_EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ENPS.Models.CAD_endereco", null)
                        .WithMany()
                        .HasForeignKey("CAD_enderedoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CAD_enderecoCAD_pessoa", b =>
                {
                    b.HasOne("ENPS.Models.CAD_endereco", null)
                        .WithMany()
                        .HasForeignKey("CAD_EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ENPS.Models.CAD_pessoa", null)
                        .WithMany()
                        .HasForeignKey("CAD_PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ENPS.Models.CAD_Telefone", b =>
                {
                    b.HasOne("ENPS.Models.CAD_empresa", null)
                        .WithMany("CAD_telefone")
                        .HasForeignKey("CAD_empresaId");

                    b.HasOne("ENPS.Models.CAD_pessoa", null)
                        .WithMany("CAD_Telefone")
                        .HasForeignKey("CAD_pessoaId");
                });

            modelBuilder.Entity("ENPS.Models.CAD_email", b =>
                {
                    b.HasOne("ENPS.Models.CAD_empresa", null)
                        .WithMany("CAD_email")
                        .HasForeignKey("CAD_empresaId");

                    b.HasOne("ENPS.Models.CAD_pessoa", null)
                        .WithMany("CAD_email")
                        .HasForeignKey("CAD_pessoaId");
                });

            modelBuilder.Entity("ENPS.Models.CAD_empresa", b =>
                {
                    b.HasOne("ENPS.Models.CAD_CNPJ", "CAD_CNPJ")
                        .WithMany()
                        .HasForeignKey("CAD_CNPJId");

                    b.HasOne("ENPS.Models.CAD_Usuario", "CAD_Usuario")
                        .WithMany()
                        .HasForeignKey("CAD_UsuarioId");

                    b.HasOne("ENPS.Models.COF_Cidade", "COF_cidade")
                        .WithMany()
                        .HasForeignKey("COF_cidadeId");

                    b.HasOne("ENPS.Models.COF_Estado", "COF_estado")
                        .WithMany()
                        .HasForeignKey("COF_estadoId");

                    b.Navigation("CAD_CNPJ");

                    b.Navigation("CAD_Usuario");

                    b.Navigation("COF_cidade");

                    b.Navigation("COF_estado");
                });

            modelBuilder.Entity("ENPS.Models.CAD_endereco", b =>
                {
                    b.HasOne("ENPS.Models.COF_Cidade", "COF_Cidade")
                        .WithMany()
                        .HasForeignKey("COF_CidadeId");

                    b.HasOne("ENPS.Models.COF_Estado", "COF_Estado")
                        .WithMany()
                        .HasForeignKey("COF_EstadoId");

                    b.Navigation("COF_Cidade");

                    b.Navigation("COF_Estado");
                });

            modelBuilder.Entity("ENPS.Models.CAD_pessoa", b =>
                {
                    b.HasOne("ENPS.Models.CAD_CPF", "CAD_CPF")
                        .WithMany()
                        .HasForeignKey("CAD_CPFId");

                    b.Navigation("CAD_CPF");
                });

            modelBuilder.Entity("ENPS.Models.CAD_pessoaCAD_email", b =>
                {
                    b.HasOne("ENPS.Models.CAD_email", "CAD_email")
                        .WithMany()
                        .HasForeignKey("CAD_emailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ENPS.Models.CAD_pessoa", "cAD_pessoa")
                        .WithMany()
                        .HasForeignKey("CAD_pessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CAD_email");

                    b.Navigation("cAD_pessoa");
                });

            modelBuilder.Entity("ENPS.Models.CAD_redeSocial", b =>
                {
                    b.HasOne("ENPS.Models.CAD_pessoa", null)
                        .WithMany("CAD_RedeSocial")
                        .HasForeignKey("CAD_pessoaId");
                });

            modelBuilder.Entity("ENPS.Models.NPS_Pesquisa", b =>
                {
                    b.HasOne("ENPS.Models.CAD_empresa", "CAD_empresa")
                        .WithMany()
                        .HasForeignKey("CAD_empresaId");

                    b.Navigation("CAD_empresa");
                });

            modelBuilder.Entity("ENPS.Models.NPS_votacao", b =>
                {
                    b.HasOne("ENPS.Models.CAD_pessoa", "CAD_Pessoa")
                        .WithMany()
                        .HasForeignKey("cAD_pessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ENPS.Models.NPS_Pesquisa", "NPS_Pesquisa")
                        .WithMany("NPS_votacao")
                        .HasForeignKey("nPS_PesquisaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CAD_Pessoa");

                    b.Navigation("NPS_Pesquisa");
                });

            modelBuilder.Entity("ENPS.Models.CAD_empresa", b =>
                {
                    b.Navigation("CAD_email");

                    b.Navigation("CAD_telefone");
                });

            modelBuilder.Entity("ENPS.Models.CAD_pessoa", b =>
                {
                    b.Navigation("CAD_email");

                    b.Navigation("CAD_RedeSocial");

                    b.Navigation("CAD_Telefone");
                });

            modelBuilder.Entity("ENPS.Models.NPS_Pesquisa", b =>
                {
                    b.Navigation("NPS_votacao");
                });
#pragma warning restore 612, 618
        }
    }
}
