// <auto-generated />
using System;
using ENPS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ENPS.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ENPS.Models.CAD_CNPJ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CAD_CNPJ");
                });

            modelBuilder.Entity("ENPS.Models.CAD_CPF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CAD_CPF");
                });

            modelBuilder.Entity("ENPS.Models.CAD_Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Fantasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("cAD_CNPJId")
                        .HasColumnType("int");

                    b.Property<int?>("cAD_UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("cidadeId")
                        .HasColumnType("int");

                    b.Property<int?>("estadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("cAD_CNPJId");

                    b.HasIndex("cAD_UsuarioId");

                    b.HasIndex("cidadeId");

                    b.HasIndex("estadoId");

                    b.ToTable("CAD_Empresa");
                });

            modelBuilder.Entity("ENPS.Models.CAD_Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CAD_EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<int?>("cOF_CidadeId")
                        .HasColumnType("int");

                    b.Property<int?>("cOF_EstadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CAD_EmpresaId");

                    b.HasIndex("cOF_CidadeId");

                    b.HasIndex("cOF_EstadoId");

                    b.ToTable("CAD_Endereco");
                });

            modelBuilder.Entity("ENPS.Models.CAD_Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CAD_CNPJId")
                        .HasColumnType("int");

                    b.Property<int?>("CAD_CPFId")
                        .HasColumnType("int");

                    b.Property<int?>("CAD_EnderecoId")
                        .HasColumnType("int");

                    b.Property<int>("ETipoPessoa")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CAD_CNPJId");

                    b.HasIndex("CAD_CPFId");

                    b.HasIndex("CAD_EnderecoId");

                    b.ToTable("CAD_Pessoa");
                });

            modelBuilder.Entity("ENPS.Models.CAD_RedeSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CAD_PessoaId")
                        .HasColumnType("int");

                    b.Property<int>("ERedeSocial")
                        .HasColumnType("int");

                    b.Property<string>("LinkRedeSocial")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CAD_PessoaId");

                    b.ToTable("CAD_RedeSocial");
                });

            modelBuilder.Entity("ENPS.Models.CAD_Telefone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CAD_EmpresaId")
                        .HasColumnType("int");

                    b.Property<int?>("CAD_PessoaId")
                        .HasColumnType("int");

                    b.Property<int>("CodigoEstado")
                        .HasColumnType("int");

                    b.Property<int>("CodigoPais")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<bool>("Princial")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CAD_EmpresaId");

                    b.HasIndex("CAD_PessoaId");

                    b.ToTable("CAD_Telefone");
                });

            modelBuilder.Entity("ENPS.Models.CAD_Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CAD_PessoaId")
                        .HasColumnType("int");

                    b.Property<int?>("CAD_emailId")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("SenhaHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SenhaSalt")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("CAD_PessoaId");

                    b.HasIndex("CAD_emailId");

                    b.ToTable("CAD_usuario");
                });

            modelBuilder.Entity("ENPS.Models.CAD_email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CAD_EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Princial")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CAD_EmpresaId");

                    b.ToTable("CAD_Email");
                });

            modelBuilder.Entity("ENPS.Models.COF_Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("CEP")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("COF_Cidade");
                });

            modelBuilder.Entity("ENPS.Models.COF_Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("COF_Estado");
                });

            modelBuilder.Entity("ENPS.Models.COF_pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("COF_pais");
                });

            modelBuilder.Entity("ENPS.Models.NPS_Pesquisa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CAD_EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFechamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdOperador")
                        .HasColumnType("int");

                    b.Property<int>("NotaMaxima")
                        .HasColumnType("int");

                    b.Property<int>("NotaMinima")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CAD_EmpresaId");

                    b.ToTable("NPS_Pesquisa");
                });

            modelBuilder.Entity("ENPS.Models.NPS_votacao", b =>
                {
                    b.Property<int>("nPS_PesquisaId")
                        .HasColumnType("int");

                    b.Property<int>("cAD_pessoaId")
                        .HasColumnType("int");

                    b.Property<string>("LinkVotacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.HasKey("nPS_PesquisaId", "cAD_pessoaId");

                    b.HasIndex("cAD_pessoaId");

                    b.ToTable("NPS_votacao");
                });

            modelBuilder.Entity("ENPS.Models.CAD_Empresa", b =>
                {
                    b.HasOne("ENPS.Models.CAD_CNPJ", "cAD_CNPJ")
                        .WithMany()
                        .HasForeignKey("cAD_CNPJId");

                    b.HasOne("ENPS.Models.CAD_Usuario", "cAD_Usuario")
                        .WithMany("CAD_Empresa")
                        .HasForeignKey("cAD_UsuarioId");

                    b.HasOne("ENPS.Models.COF_Cidade", "cidade")
                        .WithMany()
                        .HasForeignKey("cidadeId");

                    b.HasOne("ENPS.Models.COF_Estado", "estado")
                        .WithMany()
                        .HasForeignKey("estadoId");

                    b.Navigation("cAD_CNPJ");

                    b.Navigation("cAD_Usuario");

                    b.Navigation("cidade");

                    b.Navigation("estado");
                });

            modelBuilder.Entity("ENPS.Models.CAD_Endereco", b =>
                {
                    b.HasOne("ENPS.Models.CAD_Empresa", null)
                        .WithMany("enderedo")
                        .HasForeignKey("CAD_EmpresaId");

                    b.HasOne("ENPS.Models.COF_Cidade", "cOF_Cidade")
                        .WithMany()
                        .HasForeignKey("cOF_CidadeId");

                    b.HasOne("ENPS.Models.COF_Estado", "cOF_Estado")
                        .WithMany()
                        .HasForeignKey("cOF_EstadoId");

                    b.Navigation("cOF_Cidade");

                    b.Navigation("cOF_Estado");
                });

            modelBuilder.Entity("ENPS.Models.CAD_Pessoa", b =>
                {
                    b.HasOne("ENPS.Models.CAD_CNPJ", "CAD_CNPJ")
                        .WithMany()
                        .HasForeignKey("CAD_CNPJId");

                    b.HasOne("ENPS.Models.CAD_CPF", "CAD_CPF")
                        .WithMany()
                        .HasForeignKey("CAD_CPFId");

                    b.HasOne("ENPS.Models.CAD_Endereco", "CAD_Endereco")
                        .WithMany()
                        .HasForeignKey("CAD_EnderecoId");

                    b.Navigation("CAD_CNPJ");

                    b.Navigation("CAD_CPF");

                    b.Navigation("CAD_Endereco");
                });

            modelBuilder.Entity("ENPS.Models.CAD_RedeSocial", b =>
                {
                    b.HasOne("ENPS.Models.CAD_Pessoa", null)
                        .WithMany("CAD_RedeSocial")
                        .HasForeignKey("CAD_PessoaId");
                });

            modelBuilder.Entity("ENPS.Models.CAD_Telefone", b =>
                {
                    b.HasOne("ENPS.Models.CAD_Empresa", null)
                        .WithMany("telefone")
                        .HasForeignKey("CAD_EmpresaId");

                    b.HasOne("ENPS.Models.CAD_Pessoa", null)
                        .WithMany("CAD_Telefone")
                        .HasForeignKey("CAD_PessoaId");
                });

            modelBuilder.Entity("ENPS.Models.CAD_Usuario", b =>
                {
                    b.HasOne("ENPS.Models.CAD_Pessoa", "CAD_Pessoa")
                        .WithMany()
                        .HasForeignKey("CAD_PessoaId");

                    b.HasOne("ENPS.Models.CAD_email", "CAD_email")
                        .WithMany()
                        .HasForeignKey("CAD_emailId");

                    b.Navigation("CAD_email");

                    b.Navigation("CAD_Pessoa");
                });

            modelBuilder.Entity("ENPS.Models.CAD_email", b =>
                {
                    b.HasOne("ENPS.Models.CAD_Empresa", null)
                        .WithMany("cAD_email")
                        .HasForeignKey("CAD_EmpresaId");
                });

            modelBuilder.Entity("ENPS.Models.NPS_Pesquisa", b =>
                {
                    b.HasOne("ENPS.Models.CAD_Empresa", "CAD_Empresa")
                        .WithMany()
                        .HasForeignKey("CAD_EmpresaId");

                    b.Navigation("CAD_Empresa");
                });

            modelBuilder.Entity("ENPS.Models.NPS_votacao", b =>
                {
                    b.HasOne("ENPS.Models.CAD_Pessoa", "CAD_Pessoa")
                        .WithMany()
                        .HasForeignKey("cAD_pessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ENPS.Models.NPS_Pesquisa", "NPS_Pesquisa")
                        .WithMany("NPS_votacao")
                        .HasForeignKey("nPS_PesquisaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CAD_Pessoa");

                    b.Navigation("NPS_Pesquisa");
                });

            modelBuilder.Entity("ENPS.Models.CAD_Empresa", b =>
                {
                    b.Navigation("cAD_email");

                    b.Navigation("enderedo");

                    b.Navigation("telefone");
                });

            modelBuilder.Entity("ENPS.Models.CAD_Pessoa", b =>
                {
                    b.Navigation("CAD_RedeSocial");

                    b.Navigation("CAD_Telefone");
                });

            modelBuilder.Entity("ENPS.Models.CAD_Usuario", b =>
                {
                    b.Navigation("CAD_Empresa");
                });

            modelBuilder.Entity("ENPS.Models.NPS_Pesquisa", b =>
                {
                    b.Navigation("NPS_votacao");
                });
#pragma warning restore 612, 618
        }
    }
}
